name: 'Deploy to Jetfire'
description: 'Deploy a set of transformations to Jetfire from yaml manifests'
inputs:
  api-key:
    description: 'API key for authenticating with Jetfire'
    required: false
  token-url:
    description: 'Token url to use for fetching OIDC tokens'
    required: false
  project-name:
    description: 'CDF project name (only required when using OIDC credentials)'
    required: false
  scopes:
    description: 'List of OIDC scopes (comma separated)'
    required: false
  audience:
    description: 'List of OIDC audience'
    required: false
  client-id:
    description: 'OAuth2 client ID'
    required: false
  client-secret:
    description: 'OAuth2 client secret'
    required: false
  cluster:
    description: 'CDF Cluster'
    required: false
    default: 'europe-west1-1'
  path:
    description: >-
      The path to a directory containing transformation manifests.
      This is relative to $GITHUB_WORKSPACE,
      which will be the root of the repository when using actions/checkout with default settings.
    required: true
runs:
  using: composite
  steps:
    - name: Deploy using new Transformations CLI
      uses: cognitedata/transformations-cli@main
      with:
        path: ${{ inputs.path }}
        api-key: ${{ inputs.api-key }}
        client-id: ${{ inputs.client-id }}
        client-secret: ${{ inputs.client-secret }}
        cdf-project-name: ${{ inputs.project-name }}
        token-url: ${{ inputs.token-url }}
        scopes: ${{ inputs.scopes }}
        legacy-mode: true
