name: 'Deploy to Jetfire'
description: 'Deploy a set of transformations to Jetfire from yaml manifests'
inputs:
  api-key:
    description: 'API key for authenticating with Jetfire'
    required: true
  cluster:
    description: 'CDF Cluster'
    required: false
    default: 'europe-west1-1'
  path:
    description: >-
      The path to a directory containing transformation manifests.
      This is relative to $GITHUB_WORKSPACE,
      which will be the root of the repository when using actions/checkout with default settings.
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    JETFIRE_API_KEY: ${{ inputs.api-key }}
  args: ["--cluster", "${{ inputs.cluster }}", "deploy", "${{ inputs.path }}" ]
